In [8]:
import pandas as pd
#读d取数据
df = pd.read_csv("data/sales.csv",usecols=["订单号","产品类别","产品名称","销售数量","单价"])

#数据处理
df["销售金额"]=df["销售数量"]*df["单价"]
df.to_csv('data/sales_01.csv',index=False)

In [20]:
#数据查看 head,tail,describe,info,shape,columns
df1 = pd.read_csv('data/sales.csv',usecols=['订单号','产品类别','产品名称','销售数量','单价'])
df1.head(23)
df1.tail(30
         )
df1.describe()#数据的统计信息
df1.info()
df1.shape
df1.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单号     1000 non-null   int64
 1   产品类别    1000 non-null   object
 2   产品名称    1000 non-null   object
 3   销售数量    1000 non-null   int64
 4   单价      1000 non-null   int64
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

Index(['订单号', '产品类别', '产品名称', '销售数量', '单价'], dtype='object')

In [29]:
#数据选择
df2 = pd.read_csv('data/sales.csv',usecols=['订单号','产品类别','产品名称','销售数量','单价'],index_col='订单号')

#选择列
# df2['产品名称']
# df2[['产品名称','订单号']]

#选择行iloc 基于行号选择行,不包含结束位置
# df2.iloc[0]
# df2.iloc[0:5]
#loc基于索引选择哈根,包含结束位置
df2.loc[6805677496:5888085066:1]

            产品类别  产品名称  销售数量   单价
订单号
6805677496  家居用品    枕头    10  199
5857234132    食品    海苔     5   29
5888085059  电子产品  智能音箱     5  399
6823473137    食品    面包     3   29
6801664364    食品    薯片     2   19
5897064217    图书    字帖     4   29
6857752388    服装    袜子     7  -29
6898807429    服装    T恤     6  199
5875402232  电子产品   路由器     9  299
5888085066    图书    字典     2   99

In [35]:
df3 = pd.read_csv("data/sales.csv")
df3

#数据过滤
#1.过滤销售数量>=10的订单数据
# df3[df3["销售数量"]>=10]
# #2.获取产品类型为食品或图书的订单数据
# df3[df3["产品类别"].isin(["食品","图书"])]
# #3.获取单价在100-200之间订单数据
# df3[df3["单价"].between(100,200,inclusive="left")]
#4.获取销售数量>=8,并且单价>=100的订单数据
df3[(df3["销售数量"]>=8) & (df3["单价"]>=100)]
#5.获取产品类型为服装或食品,支付方式为支付宝/微信支付的订单数据
df3[df3["支付方式"].isin(["微信支付",'支付宝支付'])]

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
2    5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01
4    6801664364    食品    薯片     2   19    NaN  微信支付  2025/06/02
9    5888085066    图书    字典     2   99     青岛  微信支付  2025-06-04
14   5804178086  电子产品  蓝牙耳机    10  199     重庆  微信支付  2025-06-04
16   5812573980    食品    坚果     2   79     南京  微信支付  2025-06-05
..          ...   ...   ...   ...  ...    ...   ...         ...
985  5862231814    服装    毛衣     6  399     厦门  微信支付  2026-03-15
992  5852186744  电子产品  蓝牙耳机     2  199     广州  微信支付  2026-03-19
993  6870828210    服装    内衣     8   89     广州  微信支付  2026-03-20
994  5860722276    服装    外套     6  599     广州  微信支付  2026-03-20
995  5887473055    图书    小说    10   49     长沙  微信支付  2026-03-20

[278 rows x 8 columns]